name: CI-MAIN-Portfolio-Service
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Call-Docker-Build-Main:
    uses: Wealth-Management-Project-v1/github-actions-reusable-workflows/.github/workflows/docker-build-main.yaml@main

  Call-CI-Main:
    uses: Wealth-Management-Project-v1/github-actions-reusable-workflows/.github/workflows/ci-main.yaml@main

