name: CI-MAIN-Portfolio-Service
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Call-CI:
    uses: Wealth-Management-Project-v1/github-actions-reusable-workflows/.github/workflows/ci.yaml@main

